rate=input("What is the euro to dollar exchnage rate?:")
amount=input("How much would you like to convert?:")
rate=float(rate)
amount=float(amount)
total=rate*amount
total=float(total)
result=total-3
result=float(result)
result=print("Total after Service fee:",result)